/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./../views/errors/404.vue')['default']
    CountF: typeof import('./../views/countF.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    HomePage: typeof import('./../views/HomePage.vue')['default']
    Login: typeof import('./../views/login.vue')['default']
    Pagefour: typeof import('./../views/Pages/pagefour.vue')['default']
    PageOne: typeof import('./../views/Pages/PageOne.vue')['default']
    PageThree: typeof import('./../views/Pages/PageThree.vue')['default']
    PageTwo: typeof import('./../views/Pages/PageTwo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test11: typeof import('./../components/test11.vue')['default']
  }
}
