/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    11: typeof import('./../components/11.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    Pagefour: typeof import('./../views/Pages/pagefour.vue')['default']
    PageOne: typeof import('./../views/Pages/PageOne.vue')['default']
    PageThree: typeof import('./../views/Pages/PageThree.vue')['default']
    PageTwo: typeof import('./../views/Pages/PageTwo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
